name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.arch == 'aarch64' && 'self-hosted' || 'ubuntu-latest' }}
    continue-on-error: ${{ matrix.distro == 'jammy' }}

    strategy:
      # some versions are not builable on jammy
      fail-fast: false
      matrix:
        distro: [jammy, focal, bionic]
        arch: [x86_64, aarch64]

    env:
      DISTRO: ${{ matrix.distro }} # build target, name required by binary-builder
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: binary-builder
        uses: alekitto/renovate-internal-tools@66570d7aae5b2f04bdad7d58ad31ae3d646018fe # tag=v1.3.0
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          name: ${{ env.DISTRO }}
          path: .cache/*.tar.xz
